on:
  push:
    branches: [master]

jobs:
  prerelease:
    name: Create a pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Extract latest changelog entry
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1.1.0

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          prerelease: true
          gzip: true
          tag: unstable
          commitish: ${{ github.sha }}
          name: "Unstable - built from current master"
          body: ${{ steps.changelog_reader.outputs.log_entry }}
