on:
  push:
    branches: [master]

jobs:
  # TODO: skip if ${{ github.sha }} can be `git describe`d as an exact version
  #       tag (we'll release that separately)
  prerelease:
    name: Create a pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Extract latest changelog entry
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1.1.0

      # Explicitly delete the tag on the remote, so that the release goes back
      # into draft mode. This will reset its publication timestamp when the
      # later steps update it.
      - run: git push --delete origin unstable

      # Rewrite the tag to point to the current HEAD, otherwise we will create
      # a release with up-to-date changelog, but pointing to the old SHA to
      # which the tag previously pointed.
      - run: git tag -f unstable ${{ github.sha }}
      - run: git push -f --tags

      # Upserts the pre-release
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          prerelease: true
          tag: unstable
          name: "Unstable - built from current master"
          body: ${{ steps.changelog_reader.outputs.log_entry }}
